#!/bin/bash

## parse the command line input
parse() {
    echo $* | tr ' ' '+'
}

## perform a search with the system default web browser
search() {
    xdg-open "https://duckduckgo.com/?q=$1" 2>/dev/null
}

QUERY=$(parse $*) 
search $QUERY
