#!/bin/bash

repo=/var/www/git/$1.git
echo "About to make repo on host: $repo"
ssh git@$GIT_PUBLIC mkdir -p $repo
ssh git@$GIT_PUBLIC /usr/bin/git --git-dir=$repo init --bare 
echo "Successfully made repo at git@$GIT_PUBLIC:$repo"

mkdir $1
echo "# $1" > $1/README.md
echo "Created local $1 repository and added README"
cd $1
git init
git add README.md
git commit -m "First commit on $1"
git remote add origin git@$GIT_PUBLIC:$repo
git push -u origin master
cd ..
