#!/bin/bash

# BEFORE USING THIS SCRIPT PLEASE MAKE SURE THAT YOUR ENVIRONMENT VARIABLE 
# GIT_PUBLIC POINTS TO A SERVER WHERE YOU ARE HAVING YOUR GIT REPOSITORIES AND
# ALSO MAKE SURE THAT YOU HAVE THE PROPER SSH SETUP BETWEEN THE CLIENT AND THAT
# SERVER

# REFERENCE: https://www.youtube.com/watch?v=ju9loeXNVW0
# REFERENCE: https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server

if [ "$GIT_PUBLIC" == "" ];then
  echo "Cannot run this script without having GIT_PUBLIC set!"
  exit
fi

repo=/srv/git/$1.git
echo "About to make repo on host: $repo"
ssh git@$GIT_PUBLIC mkdir -p $repo
ssh git@$GIT_PUBLIC /usr/bin/git --git-dir=$repo init --bare 
echo "Successfully made repo at git@$GIT_PUBLIC:$repo"

mkdir $1
echo "# $1" > $1/README.md
echo "Created local $1 repository and added README"
cd $1
git init
git add README.md
git commit -m "First commit on $1"
git remote add origin git@$GIT_PUBLIC:$repo
git push -u origin master
ssh git@$GIT_PUBLIC touch $repo/git-daemon-export-ok
cd ..
