#!/bin/bash

name="$(echo "$1" | sed 's/./\U&/')"
import=""
if [ "$name" == "App" ]; then import="import React from \"react\"\n\n"; fi 
echo -ne "${import}export default function $name() {
    return (
    <div></div>
    )
}\n"
